### ISSUE TITLE
MIDI implementation doesn't work on Firefox

### ISSUE THREAD

**Issue by michaelkolesidis** [michaelkolesidis/javascript-software-synthesizer#13]
**Describe the bug**
The WEBMIDI.js doesn't  work on Firefox

**To Reproduce**
1. Open the JSS-01 
2. The MIDI display appears empty
3. MIDI keyboard is unresponsive
4. This error appears in the console:

![Screenshot from 2022-03-22 15-32-47](https://user-images.githubusercontent.com/15524442/159493555-03fb2cb4-ffd6-4b3b-b923-df511d602e3a.png)

**Desktop :**
 - Ubuntu Linux 20.04 LTS
 - Mozilla Firefox 98.0.1 (64-bit)

**Comment by mcochris** [comment]
I don't think Firefox supports the MIDI input API: [link](https://bugzilla.mozilla.org/show_bug.cgi?id=836897). There are FF extensions that may add that function: [link]https://addons.mozilla.org/en-US/firefox/addon/midi-input-provider/

Let us know if that works!

**Comment by michaelkolesidis** [comment]
Thanks for the information, it worked! I will add it in the readme file at some point.

**Comment by michaelkolesidis** [comment]
Browser requirements updated
https://github.com/michaelkolesidis/javascript-software-synthesizer/blob/main/README.md#browser-requirements

**Comment by michaelkolesidis** [comment]
Thanks for your time and y our valuable contributions, you are now added to the project contributors list.
https://github.com/michaelkolesidis/javascript-software-synthesizer#contributors
