### ISSUE TITLE
Sound won't stop using external MIDI controller

### ISSUE THREAD

**Issue by mcochris** [michaelkolesidis/javascript-software-synthesizer#18]
Thanks for JSS! I have a Yamaha MX synth connected via USB to my Win 10 Edge browser. JSS sees the synth and responds to the synth keyboard. But once a note is played, it doesn't stop playing until I refresh the web page. JSS responds as expected when using the web page keyboard.

**Comment by michaelkolesidis** [comment]
Thanks for the issue Chris! I had the chance to test the JSS with a couple of MIDI controllers and I never had the issue you are describing. Could you please use another MIDI controller and inform me whether the problem persists? Otherwise, it is possible that this behaviour is caused by the Yamaha and/or its interaction with the Web MIDI API.

**Comment by mcochris** [comment]
Thanks for the reply Michael. I don't have another MIDI controller to try. I did download MIDIOX [http://www.midiox.com/](http://www.midiox.com/) and it can see the keyup commands, but that only means Windows can see key up/down. If I try [https://www.midimonitor.com/](https://www.midimonitor.com/) it does not see keyup. So it looks like my synth may not work with the MIDI web API. Rats! Pictures attached or it didn't happen 😊

![Screenshot 2022-04-10 072955](https://user-images.githubusercontent.com/46349138/162616957-07a99aff-22fe-4570-84cc-326e9ef578be.png)
![Screenshot 2022-04-10 073119](https://user-images.githubusercontent.com/46349138/162616959-36362e07-c7c9-48f0-af93-68cd78664d39.png)
![Screenshot 2022-04-10 074708](https://user-images.githubusercontent.com/46349138/162616961-5ca42cb8-cf87-4166-990d-e46274e5df19.png)

**Comment by michaelkolesidis** [comment]
Thanks for the thorough reply and explanation!
