### ISSUE TITLE
How to run it locally?

### ISSUE THREAD

**Issue by OmarShehata** [michaelkolesidis/javascript-software-synthesizer#27]
I was confused for a while because I couldn't find instructions for how to actually run it, nor an online demo. I was also looking for a `npm start` or `npm serve` etc command in the package.json. 

Eventually I realized you can serve the root directly in a local http server and the `index.html` that's in there is the entry point. Is that how others run it?

It'd be great to include a line in the README about that, or perhaps an npm command for starting a local server to make it more convenient. Thank you for the awesome library!

**Comment by michaelkolesidis** [comment]
Thanks for  your kind words! You can run the JavaScript Software Synthesizer locally easily by using a VSCode extension like **Live Server** ([Live Server on the Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer)) or Python's **http.server** module.

For more information, please refer to MDN's excellent article: [MDN article](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Tools_and_setup/set_up_a_local_testing_server)

PS. There is an online demo available at [https://javascript-software-synthesizer.netlify.app/](https://javascript-software-synthesizer.netlify.app/)

**Comment by OmarShehata** [comment]
Thank you so much!

**Comment by michaelkolesidis** [comment]
You are now added as a contributor to the project.

**Reason**: Created isse
**List**: [Contributors](https://github.com/michaelkolesidis/javascript-software-synthesizer#contributors)
**Commit**:  cd9c472
