### ISSUE TITLE
Bug: All keys stop playing when single key is released

### ISSUE THREAD

**Issue by joshenx** [michaelkolesidis/javascript-software-synthesizer#28]
**Describe the bug**
All keys stop playing when single key is released

**To Reproduce**

1. Press multiple keys e.g. "ASD"
2. Release D
3. All keys stop emitting sound even though sounds on "AS" keys should play

**Expected behavior**
sounds on "AS" keys should play

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser : CHrome
- Version: 114.0.5735.134 (Official Build) (64-bit)

**Additional context**

**Comment by michaelkolesidis** [comment]
Thanks for submitting an issue! I am aware of the bug, but I am yet to come up with a fix. Interestingly enough, if you use a MIDI keyboard, the bug does not occur. 

Feel free to have a look into the issue if you wish, and do not hesitate to ask me anything that might help.
