### ISSUE TITLE
Computer keyboard playability only works when keyboard language is set to English

### ISSUE THREAD

**Issue by mamarmar** [michaelkolesidis/javascript-software-synthesizer#7]
**Describe the bug**
One of the synthesizer playability options is using the computer keyboard. Certain letters are matched to certain notes (A-L plus some letters from the above line), and pressing one of the letters triggers the synthesizer to play a certain note. The problem is that when the keyboard language is set to another language (in my case Greek) it stops responding.

**To Reproduce**
1. Go to  the synthesizer'smain page
2. Try to play the synthesizer using the computer keyboard w

**Desktop (please complete the following information):**
 - OS: macOS 11 Big Sur 11.4
 - Browser: Chrome
 - Version 99

**Comment by michaelkolesidis** [comment]
Fixed with commit 6a9e657
